server:
  port: 8081
spring:
  application:
    name: spaceships
    is_kafka_enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
    bindings:
      input:
        destination: spaceships_topic
      output:
        destination: filtered_spaceships_topic
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8084
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      topic: ${spring.application.name}-output
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
